/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "evaluation-0": "#B00020",
        "secondary": "#bb0308",
        "inverse-on-surface": "#f0f0f8",
        "national-red": "#DA251D",
        "primary-container": "#00429d",
        "evaluation-1": "#FB8C00",
        "tertiary-fixed": "#ffdbce",
        "surface-container-high": "#e8e7f0",
        "on-tertiary-fixed": "#370e00",
        "surface-tint": "#2b5ab6",
        "surface": "#faf8ff",
        "on-tertiary-container": "#ff9d76",
        "on-primary-container": "#97b4ff",
        "on-surface-variant": "#434652",
        "evaluation-3": "#7CB342",
        "on-error-container": "#93000a",
        "surface-variant": "#e2e2ea",
        "academic-blue": "#00429D",
        "surface-container-low": "#f3f3fb",
        "tertiary": "#5b1c00",
        "on-tertiary": "#ffffff",
        "evaluation-2": "#FDD835",
        "outline": "#737783",
        "primary-fixed": "#d9e2ff",
        "tertiary-container": "#802b00",
        "tertiary-fixed-dim": "#ffb599",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "secondary-container": "#e02a21",
        "primary-fixed-dim": "#b0c6ff",
        "surface-dim": "#d9d9e2",
        "on-primary-fixed": "#001945",
        "secondary-fixed": "#ffdad5",
        "on-secondary-fixed-variant": "#930004",
        "on-background": "#1a1b21",
        "outline-variant": "#c3c6d4",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b0c6ff",
        "surface-administrative": "#F8F9FA",
        "on-primary-fixed-variant": "#00419c",
        "secondary-fixed-dim": "#ffb4a9",
        "surface-container": "#ededf5",
        "on-secondary-container": "#fffbff",
        "border-neutral": "#DEE2E6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#7f2b00",
        "background": "#faf8ff",
        "surface-container-highest": "#e2e2ea",
        "on-secondary-fixed": "#410001",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#1a1b21",
        "primary": "#002d70",
        "inverse-surface": "#2e3036",
        "evaluation-4": "#2E7D32"
      },
      fontFamily: {
        "headline-lg": ["Public Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "monospace"],
        "headline-xl": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"]
      },
      keyframes: {
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        }
      },
      animation: {
        blob: "blob 7s infinite",
        "fade-in": "fadeIn 0.3s ease-out forwards",
      }
    },
  },
  plugins: [],
}
